server:
  port: 8880

spring:
  datasource:
    url: jdbc:mysql://192.168.31.177/wiki?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: mysql123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.31.177
    port: 6379
    password: redisyyds123
    database: 1

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

logging:
  level:
    com:
      jiawa:
        wiki:
          mapper: trace
